CREATE TABLE BOARD 
(
  NO NUMBER NOT NULL 
, SUBJECT VARCHAR2(255) NOT NULL 
, CONTENT VARCHAR2(255) NOT NULL 
, WRITER VARCHAR2(255) 
, READ_COUNT NUMBER DEFAULT 0 
, CREATED_DATE TIMESTAMP 
, CONSTRAINT BOARD_PK PRIMARY KEY 
  (
    NO 
  )
  ENABLE 
);